
version: "3.3"

services:
  app:
    image: azizjouini/passport-app-saml:latest
    pull_policy: always
    volumes:
      - /etc/ssl/certs/ssl-cert-snakeoil.pem:./cert/ssl-cert-snakeoil.pem
      - /etc/ssl/private/ssl-cert-snakeoil.key:./cert/ssl-cert-snakeoil.key
      - /etc/ssl/aai/dfn-aai.pem:./cert/dfn-aai.pem
    networks:
     - back
    ports:
     - "3031:3031"
networks:
  back:    
    driver: bridge
