
version: "3.3"

services:
  app:
    image: azizjouini/passport-app-saml:latest
    pull_policy: always
    networks:
     - back
    ports:
     - "3031:3031"
networks:
  back:    
    driver: bridge
