
version: "3.3"

services:
  app:
    #image: azizjouini/passport-app-saml:latest
    build: .
    pull_policy: always
    volumes:
      #replace with real certificates and key paths from your machine 
      - /etc/ssl/certs/ssl-cert-snakeoil.pem:/app/cert/ssl-cert-snakeoil.pem
      - /etc/ssl/private/ssl-cert-snakeoil.key:/app/cert/ssl-cert-snakeoil.key
      - /etc/ssl/aai/dfn-aai.pem:/app/cert/dfn-aai.pem
    networks:
     - back
    ports:
     - "3031:3031"

  py-app:
    build: ./flask-app
    # volumes:
    ports:
      - "8081:8081"
    networks:
     - back


networks:
  back:    
    driver: bridge
    
#osso service provider
  # osso:
  #   image: sambauch/osso
  #   networks:
  #     - back
  #   expose:
  #     - 5432
  #   ports:
  #     - "8080:8080"

  # kong-database:
  #   image: postgres:9.6
  #   container_name: kong-database
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=kong
  #     - POSTGRES_DB=kong
  #     - POSTGRES_PASSWORD=kong
  #   volumes:
  #     - "db-data-kong-postgres:/var/lib/postgresql/data"
  #   networks:
  #    - back

  # kong-migrations:
  #   image: kong
  #   environment:
  #     - KONG_DATABASE=postgres
  #     - KONG_PG_HOST=kong-database
  #     - KONG_PG_PASSWORD=kong
  #     - KONG_CASSANDRA_CONTACT_POINTS=kong-database
  #   command: kong migrations bootstrap
  #   restart: on-failure
  #   depends_on:
  #     - kong-database
  #   networks:
  #    - back

  # kong:
  #   image: kong
  #   container_name: kong
  #   environment:
  #     - LC_CTYPE=en_US.UTF-8
  #     - LC_ALL=en_US.UTF-8
  #     - KONG_DATABASE=postgres
  #     - KONG_PG_HOST=kong-database
  #     - KONG_PG_USER=kong
  #     - KONG_PG_PASSWORD=kong
  #     - KONG_CASSANDRA_CONTACT_POINTS=kong-database
  #     - KONG_PROXY_ACCESS_LOG=/dev/stdout
  #     - KONG_ADMIN_ACCESS_LOG=/dev/stdout
  #     - KONG_PROXY_ERROR_LOG=/dev/stderr
  #     - KONG_ADMIN_ERROR_LOG=/dev/stderr
  #     - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
  #   restart: on-failure
  #   ports:
  #     - 8000:8000
  #     - 8442:8442
  #     - 8001:8001
  #     - 8444:8444
  #   links:
  #     - kong-database:kong-database
  #   depends_on:
  #     - kong-migrations
  #   networks:
  #    - back

  # konga:
  #   image: pantsel/konga
  #   ports:
  #     - 1337:1337
  #   links:
  #     - kong:kong
  #   container_name: konga
  #   environment:
  #     - NODE_ENV=production
  #   networks:
  #    - back
      
# testing keycloak service 
#  keycloak:
#    container_name: keycloak
#    image: "jboss/keycloak:15.0.2"
#     volumes:
#      - ./kc-data:/var/lib/postgresql/data/
#    ports:
#      - "8080:8080"
#      - "8787:8787" # debug port
#    networks:
#      - back



# volumes:
#   db-data-kong-postgres:


